### ISSUE TITLE
Deprecate in favour of WASM fallback

### ISSUE THREAD

**Issue by mhsjlw** [ProtoDef-io/protodefc-prebuilt#4]
This will require new versions of Node, but remove this repository and build using Rust on the host if it is installed, or use a WASM release otherwise.

**Comment by mhsjlw** [comment]
No, we build the WASM blobs and distribute them inside the module (since they are cross platform), and we use them if the run-time supports them. Otherwise, we build the module using neon (meaning they need Rust)

So they either use Node 8+, or they have Rust installed. Is that reasonable to ask?

**Comment by rom1504** [comment]
Node8 is reasonable yes
